export interface Booking_Cards{
    id: string,
    name:string,
    time:string,
    status:"Confirmed" | "Pending",
    service:string,
    duration:string,
    bgcolor:string,
    color:string,

}

export const Bookings:Booking_Cards[]=[
    {
        id:"1",
        name:"Sarah Johnson",
        time:"1.5 hours",
        status:"Confirmed",
        duration:"1.5 hours",
         color: "text-green-500",
         bgcolor: "bg-green-100",
         service:"Hair Cut & Styling - 9:00 AM",
    },
    {
    id: "2",
    name: "Michael Brown",
    service: "Beard Trim - 11:00 AM",
    time: "30 minutes",
    duration: "30 minutes",
    status: "Confirmed",
    color: "text-blue-500",
    bgcolor: "bg-blue-100",
    },
    {
        id: "3",
    name: "Emma Wilson",
    service: "Full Service - 2:00 PM",
    time: "2 hours",
    duration: "2 hours",
    status: "Pending",
    color: "text-orange-500",
    bgcolor: "bg-orange-100",
    },
    {
        id: "4",
    name: "David Lee",
    service: "Hair Wash & Cut - 4:30 PM",
    time: "1 hour",
    duration: "1 hour",
    status: "Confirmed",
    color: "text-purple-500",
    bgcolor: "bg-purple-100",
    },
    {
        id: "5",
    name: "Lisa Anderson",
    service: "Color Treatment - 6:00 PM",
    time: "2.5 hours",
    duration: "2.5 hours",
    status: "Confirmed",
    color: "text-teal-500",
    bgcolor: "bg-teal-100",
    },
     {
        id:"6",
        name:"Sarah Johnson",
        time:"1.5 hours",
        status:"Confirmed",
        duration:"1.5 hours",
         color: "text-green-500",
         bgcolor: "bg-green-100",
         service:"Hair Cut & Styling - 9:00 AM",
    },
     {
        id:"7",
        name:"Sarah Johnson",
        time:"1.5 hours",
        status:"Confirmed",
        duration:"1.5 hours",
         color: "text-green-500",
         bgcolor: "bg-green-100",
         service:"Hair Cut & Styling - 9:00 AM",
    },
     {
        id:"8",
        name:"Sarah Johnson",
        time:"1.5 hours",
        status:"Confirmed",
        duration:"1.5 hours",
         color: "text-green-500",
         bgcolor: "bg-green-100",
         service:"Hair Cut & Styling - 9:00 AM",
    },
     {
        id:"9",
        name:"Sarah Johnson",
        time:"1.5 hours",
        status:"Confirmed",
        duration:"1.5 hours",
         color: "text-green-500",
         bgcolor: "bg-green-100",
         service:"Hair Cut & Styling - 9:00 AM",
    },
    {
         id: "10",
    name: "Emma Wilson",
    service: "Full Service - 2:00 PM",
    time: "2 hours",
    duration: "2 hours",
    status: "Pending",
    color: "text-orange-500",
    bgcolor: "bg-orange-100",
    },
    {
         id: "11",
    name: "Lisa Anderson",
    service: "Color Treatment - 6:00 PM",
    time: "2.5 hours",
    duration: "2.5 hours",
    status: "Confirmed",
    color: "text-teal-500",
    bgcolor: "bg-teal-100",
    },
    {
        id: "12",
    name: "Michael Brown",
    service: "Beard Trim - 11:00 AM",
    time: "30 minutes",
    duration: "30 minutes",
    status: "Confirmed",
    color: "text-blue-500",
    bgcolor: "bg-blue-100",
    }

]